apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bgxvymt3e-python 
  janus-idp.io/tekton: bgxvymt3e-python
  backstage.io/kubernetes-id: bgxvymt3e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bgxvymt3e-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml