apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bgxvymt3e-python
  janus-idp.io/tekton: bgxvymt3e-python
  backstage.io/kubernetes-id: bgxvymt3e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bgxvymt3e-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
