apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bgxvymt3e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bgxvymt3e-python 
  name: bgxvymt3e-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bgxvymt3e-python 
